### ISSUE TITLE
代码是否还没开发完的呢

### ISSUE THREAD

**Issue by suruozhong** [wechaty/java-wechaty#15]
1，我看好像只实现了五个事件，ScanListener，MessageListener，RoomJoinListener，RoomLeaveListener，RoomTopicListener，其它的事件监听是不是还没完成的呢
2，建议事件名称不要使用魔法值，加一个常量类，调用常量类来获取事件名称，我翻源码才知道所有事件的名称怎么写
![image](https://user-images.githubusercontent.com/22618493/82773415-8f8d0480-9e74-11ea-920d-ef85e2953804.png)

**Comment by huan** [comment]
> 建议事件名称不要使用魔法值，加一个常量类，调用常量类来获取事件名称，我翻源码才知道所有事件的名称怎么写

That's a great suggestion!

In TypeScript, we can treat the string value as a literal type, it's exactly as same as an ENUM of the string and the VSCode IDE can show all values very easily.

In Java, I believe we need to create an ENUM to contain those values as well.

**Comment by diaozxin007** [comment]
主要是为了对标，TypeScript 的 api。将来可以考虑使用方法名表示，类似写成 OnMessage()，OnRoomJoin() 。

**Comment by luckywaa** [comment]
> > 建议事件名称不要使用魔法值，加一个常量类，调用常量类来获取事件名称，我翻源码才知道所有事件的名称怎么写
> 
> That's a great suggestion!
> 
> In TypeScript, we can treat the string value as a literal type, it's exactly as same as an ENUM of the string and the VSCode IDE can show all values very easily.
> 
> In Java, I believe we need to create an ENUM to contain those values as well.

用枚举可能也不错
