### ISSUE TITLE
message事件一直不触发

### ISSUE THREAD

**Issue by suruozhong** [wechaty/java-wechaty#17]
1，之前用使用java-wechaty-getting-started或者源码java-wechaty都能跑通，最近创建一个新项目，导入java-wechaty包，可以跑起来，可以扫码登录（scan会触发），但接收不到消息
（message不会触发）。再拿java-wechaty-getting-started去跑也不会触发message了

2，我跑两个java-wechaty的demo，同一个token，登录同一微信号，两个都在运行，正常打印log，正常来说，不是会掉线一个么？

以上使用的都是puppet-hostie的token
![image](https://user-images.githubusercontent.com/22618493/82856836-bcf3b400-9f41-11ea-9da9-bfdedca39d81.png)
![image](https://user-images.githubusercontent.com/22618493/82856852-d39a0b00-9f41-11ea-93e2-cc5c24984fb3.png)

**Comment by huan** [comment]
Is there any difference between the `event` and `eventName`? I saw you use all those two with different events.

**Comment by suruozhong** [comment]
我认为是没有区别，在源码里，都是同样类型，但却不一样的命名
![image](https://user-images.githubusercontent.com/22618493/82860453-3abcbd00-9f4c-11ea-8189-0644c5cb1249.png)
