### ISSUE TITLE
Java version without displaying the login QR code

### ISSUE THREAD

**Issue by windiam** [wechaty/java-wechaty#34]
Java version without displaying the login QR code
![微信截图_20200609094222](https://user-images.githubusercontent.com/9796262/84096888-a5cebf00-aa35-11ea-92ef-c693494edb82.png)

**Comment by diaozxin007** [comment]
plz make sure the terminal charset is “UTF-8”.

**Comment by windiam** [comment]
> plz make sure the terminal charset is “UTF-8”.

It’s "UTF-8".

**Comment by diaozxin007** [comment]
try execute
```shell
echo $LC_CTYPE
echo $LANG
```
in your terminal.

**Comment by windiam** [comment]
The system is Windows.
