### ISSUE TITLE
How to qet a new qrcode

### ISSUE THREAD

**Issue by windiam** [wechaty/java-wechaty#35]
Everytime  run the program，the qrcode is same. How to qet a new qrcode

**Comment by su-chang** [comment]
Check your `java-wechaty` version first.

If no problem with the version, please show your token to `百年`.

**Comment by su-chang** [comment]
**Conclusion**
If you logout WeChat account in WeChat APP, it will not emit new QR code now, you could regard it as a bug, we will fix it as quick as possible.
