### ISSUE TITLE
https://wechaty.js.org/v/zh/api/room-invitation  对应的java实现是如下三个方法么

### ISSUE THREAD

**Issue by landgreenland** [wechaty/java-wechaty#50]
.onRoomLeave((room, leaverList, remover, date) -> {
          })
           .onRoomTopic((room, newTopic, oldTopic, changer, date) ->   {
                }
            )
            .onRoomJoin((room, inviteeList, inviter, date) -> {

**Comment by diaozxin007** [comment]
yes , 你已经摸清楚了 java-wechaty 的精髓

**Comment by landgreenland** [comment]
> yes , 你已经摸清楚了 java-wechaty 的精髓

您测试过没有 ，好像 .onRoomJoin((room, inviteeList, inviter, date)  这个实践捕捉不到

**Comment by diaozxin007** [comment]
@redmaple1

**Comment by landgreenland** [comment]
> @redmaple1

可以了。是我这里用的问题，谢谢。  一下代码是可以用的
.onRoomJoin((room, inviteeList, inviter, date) -> {
                room.say("", inviteeList);
                room.say(inviter.name() + "邀请了你");

**Comment by redmaple1** [comment]
> > @redmaple1
> 
> 可以了。是我这里用的问题，谢谢。 一下代码是可以用的
> .onRoomJoin((room, inviteeList, inviter, date) -> {
> room.say("", inviteeList);
> room.say(inviter.name() + "邀请了你");

ok~
