### ISSUE TITLE
    SDK的bug：   List<Contact> li =  room.memberAll(null);    获取不到li中的Contact

### ISSUE THREAD

**Issue by landgreenland** [wechaty/java-wechaty#51]
fun memberList(): List<Contact> {

        val memberIdList = wechaty.getPuppet().roomMemberList(this.id).get()

        if (CollectionUtils.isEmpty(memberIdList)) {
            return listOf()
        }

        val contactList = memberIdList.map {
            wechaty.contactManager.load(id)
        }
        return contactList

    }

**Comment by landgreenland** [comment]
room.memberList()   

获取的也不是  List <   Contact   >  

得到的是room相关的信息 
![image](https://user-images.githubusercontent.com/67773401/86899052-0daf1d00-c13c-11ea-9845-7e8e73268338.png)
![image](https://user-images.githubusercontent.com/67773401/86899074-169fee80-c13c-11ea-8b39-261fa1440bc5.png)

**Comment by diaozxin007** [comment]
并非 room 相关信息，是用户在该 room 中的 id
