### ISSUE TITLE
心跳包解析异常

### ISSUE THREAD

**Issue by windiam** [wechaty/java-wechaty#59]
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "timeout" (class io.github.wechaty.schemas.EventHeartbeatPayload), not marked as ignorable (one known property: "data"]) at [Source: (String)"{"data":"heartbeat","timeout":60000}"; line: 1, column: 36] (through reference chain: io.github.wechaty.schemas.EventHeartbeatPayload["timeout"])

**Comment by diaozxin007** [comment]
请提供 token 的类型

**Comment by windiam** [comment]
> 请提供 token 的类型

donut-token

**Comment by jcai** [comment]
```
    val om = new ObjectMapper()
    om.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)

```

**Comment by diaozxin007** [comment]
新版本已经修复
