### ISSUE TITLE
心跳一直超时报错

### ISSUE THREAD

**Issue by suruozhong** [wechaty/java-wechaty#62]
![1git](https://user-images.githubusercontent.com/22618493/87397070-548e8e00-c5e6-11ea-8d55-2ccfb78ed873.png)
![2git](https://user-images.githubusercontent.com/22618493/87397134-67a15e00-c5e6-11ea-995d-2b688b93b5a8.jpg)

每天十几兆的日志全是这个

**Comment by jcai** [comment]
```
    val om = new ObjectMapper()
    om.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)

```

**Comment by diaozxin007** [comment]
fix
