### ISSUE TITLE
Unused import cause failure in JDK11

### ISSUE THREAD

**Issue by Charles-Wu-Chen** [wechaty/java-wechaty#72]
this import is never used in the code (io.github.wechaty.user.manager.FriendshipManager).  And it causes compilation failure in jdk 11.0.5.hs-adpt (AdoptOpenJDK).

import com.sun.xml.internal.ws.message.PayloadElementSniffer

This line shall be able to be remove safely .

**Comment by diaozxin007** [comment]
ok will fix next version
