### ISSUE TITLE
【报错】cannot get ip by token, check token

### ISSUE THREAD

**Issue by 837099748** [wechaty/java-wechaty#74]
io.github.wechaty.grpc.GrpcPuppet        : cannot get ip by token, check token
是我需要部署到公网吗？部署到公网了也是这个错误，请问怎么解决呢？

**Comment by Freud-Ju** [comment]
我一直本地起java-wechaty-getting-started也是这个错误，他们给我说token无效。我也不知道为什么给的token没用。我现在什么都没干成
我用java-wechaty-getting-started

`public static void main(String[] args) throws Exception {

        final String token = "puppet_padplus_xxxxxxxxxxxxxxxxx";

        if (StringUtils.isBlank(token)) {

            System.out.println("Error: WECHATY_PUPPET_HOSTIE_TOKEN is not found in the environment variables");
            System.out.println("You need a TOKEN to run the Java Wechaty. Please goto our README for details");
            System.out.println("https://github.com/wechaty/java-wechaty-getting-started/#wechaty_puppet_hostie_token");

            throw new Exception("need a token");
        }
        Wechaty bot = Wechaty.instance(token);

        bot.onScan((qrcode, statusScanStatus, data) -> {
            System.out.println(QrcodeUtils.getQr(qrcode));
            System.out.println("Online Image: https://wechaty.github.io/qrcode/" + qrcode);
        });

        bot.onMessage(message -> {

            Contact from = message.from();
            Room room = message.room();

            String text = message.text();

            if (StringUtils.equals(text, "#ding")) {
                if (room != null) {
                    room.say("dong");
                } else {
                    from.say("dong");
                }
            }
        });

        bot.start(true);

    }` 
报错是cannot get ip by token, check token

我用java-wechaty里面的example跑
`public static void main(String[] args){

        Wechaty bot = Wechaty.instance("puppet_padplus_xxxxxxxxxxxxxx")
            .onScan((qrcode, statusScanStatus, data) -> System.out.println(QrcodeUtils.getQr(qrcode)))
            .onLogin(user -> System.out.println(user))
            .onMessage(message -> {
                Room room = message.room();
                String text = message.text();
                if (StringUtils.equals(text, "#ding")) {
                    if (room != null) {
                        room.say("dong");
                    }
                }
            }).start(true);
    }`
然后没有任何的输出，程序就结束了

**Comment by liuxing7954** [comment]
所以还是没解决办法是吗? 
token是没问题的, 我用ts版本已经运行成功了
